### PR TITLE
Fix wrong usage of hpack_integer:decode

### LINKED ISSUE #2: Issues decoding a hpack string
I'm consuming a service via HTTP2 and am having intermittent problems parsing responses from upstream. I've traced this to `hpack_string` parsing the length of the string incorrectly. Below is an example that shows this:

``` erlang
1> {_, Ctx1} = hpack:decode(<<136,64,133,29,117,33,99,73,157,102,28,2,113,171,248,86,195,130,251,235,96,106,244,43,66,44,45,173,135,3,176,185,131,11,78,96,117,223>>, hpack:new_decode_context()).
2> hpack:decode(<<136,31,47,155,132,34,192,235,184,2,179,143,53,10,193,117,182,150,116,76,222,88,12,129,203,238,137,167,3,117,207>>, Ctx1). 
** exception error: no match of right hand side value <<184,66,44,14,187,128,43,56,243,80,172,23,91,105,103,68,
                                                        205,229,128,200,28,190,232,154,112,55,92,15:4>>
     in function  hpack_string:decode/1 (/Users/omarkj/hpack/_build/default/lib/hpack/src/hpack_string.erl, line 12)
     in call from hpack:decode_literal_header_never_indexed/3 (/Users/omarkj/hpack/_build/default/lib/hpack/src/hpack.erl, line 143)
```

### PR DESCRIPTION
**Pull request by dthul**
Resolves #2

### CODE REVIEW

**Comment by joedevivo** [comment]
Please include tests.

**Comment by dthul** [comment]
I added some tests.

**Comment by dthul** [comment]
Do you think that this is mergeable in its current state?
Otherwise I need to roll out a custom fork of Chatterbox since I need this in production soon.

**Comment by joedevivo** [comment]
I merged it, and then tagged it at `0.1.0`

**Pull request merged**
